all:
	make -C dcman
	make -C pspdecrypt
	make -C libpsardumper
	make -C resurrection
	make -C installer

clean:
	make -C dcman clean
	make -C pspdecrypt clean
	make -C libpsardumper clean
	make -C resurrection clean
	make -C installer clean