#ifndef __TRANS_H__
#define __TRANS_H__

#define STRING (char *)g_messages

enum {
	STR_INSTALL = 0,
	STR_BATTERY,
	STR_EXIT,
	STR_CONVERT_TO_NORMAL,
	STR_CONVERT_TO_PANDORA,
	STR_CONVERT_TO_AUTOBOOT,
	STR_DESPERTAR_DEL_CEMENTERIO,
	STR_BATTERY_OPERATIONS,
	STR_YOUR_CURRENT_FIRMWARE_IS_UNSUPPORTED,
	STR_SELECT_YOUR_VERSION,
	STR_INSUFFICIENT_RESERVED_SECTOR_SPACE,
	STR_NOT_FOUND_AT_ROOT,
	STR_AN_EXISTING_INSTALLATION_WAS_FOUND,
	STR_INVALID_FILE_SIZE,
	STR_CREATING_MAGIC_MEMORY_STICK,
	STR_VERIFYING_PBP_VER,
	STR_INVALID_OR_CORRUPTED_PBP,
	STR_CREATING_DIRECTORIES,
	STR_ERROR_CREATING_DIRECTORIES,
	STR_EXTRACTING_UPDATER_MODULES,
	STR_CANNOT_DECRYPT_DATA_PSP,
	STR_ERROR_EXTRACTING_MODULE,
	STR_ERROR_OPENING_PBP,
	STR_LOADING_PSAR,
	STR_ERROR_READING_PBP,
	STR_PSPPSARINIT_FAILED,
	STR_PSAR_DECODE_ERROR,
	STR_CANNOT_FIND_PATH_OF,
	STR_INSTALLING_FILE,
	STR_ERROR_INSTALLING_FILE,
	STR_CANNOT_DECRYPT_COMMON_TABLE,
	STR_CANNOT_DECRYPT_GENERATION_TABLE,
	STR_INJECT_IPL,
	STR_ERROR_OPENING_MSSTOR,
	STR_SAVING_REGISTERY,
	STR_PLEASE_HOLD_THE_KEY,
	STR_INSTALL_COMPLETE,
	STR_PSP_HARDWARE_NOT_SUPPORTED,
	STR_CONVERT_BATTERY,
	STR_NORMAL_BATTERY,
	STR_PANDORA_BATTERY,
	STR_AUTOBOOT_BATTERY,
	STR_CONVERTING_TO,
	STR_NO_NEED_TO_CHANGE_SERIAL,
	STR_UNABLE_TO_WRITE_THE_SERIAL,
	STR_BATTERY_MODE_SERIAL,
	MSG_END
};

void vpl_init(void);
void vpl_finish(void);
void select_language(void);

#endif

